import {
  UilSearch,
  UilSearchAlt,
  UilSearchMinus,
  UilSearchPlus,
  UilFileSearchAlt,
  UilEstate,
  UilShoppingBag,
  UilListUl,
  UilPlus,
  Uil0Plus,
  Uil10Plus,
  Uil12Plus,
  Uil13Plus,
  Uil16Plus,
  Uil17Plus,
  UilPlusCircle,
  UilPlusSquare,
  Uil3Plus,
  UilCrosshair,
  UilCrosshairAlt,
  UilHunting,
  UilFocusTarget,
  UilCrosshairs,
} from '@iconscout/react-unicons';

export const IconMap = {
  home: UilEstate,
  cart: UilShoppingBag,
  items: UilListUl,
  plus: UilPlus,
  $0Plus: Uil0Plus,
  $10Plus: Uil10Plus,
  $12Plus: Uil12Plus,
  $13Plus: Uil13Plus,
  $16Plus: Uil16Plus,
  $17Plus: Uil17Plus,
  plusCircle: UilPlusCircle,
  plusSquare: UilPlusSquare,
  $3Plus: Uil3Plus,
  search: UilSearch,
  searchAlt: UilSearchAlt,
  searchMinus: UilSearchMinus,
  searchPlus: UilSearchPlus,
  fileSearchAlt: UilFileSearchAlt,
  crosshair: UilCrosshair,
  crosshairAlt: UilCrosshairAlt,
  hunting: UilHunting,
  focusTarget: UilFocusTarget,
  crosshairs: UilCrosshairs,
};
